/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Array */

#ifndef _Included_Array
#define _Included_Array
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Array
 * Method:    sumAndSquare
 * Signature: ([I)[I
 */
JNIEXPORT jintArray JNICALL Java_Array_sumAndSquare
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
