/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Dim2Arr */

#ifndef _Included_Dim2Arr
#define _Included_Dim2Arr
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Dim2Arr
 * Method:    get2DimArr
 * Signature: (I)[[I
 */
JNIEXPORT jobjectArray JNICALL Java_Dim2Arr_get2DimArr
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
