/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class S */

#ifndef _Included_S
#define _Included_S
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     S
 * Method:    pass
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_S_pass
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
